{{- if .Values.agent.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "parca.fullname" . }}-agent
  labels:
    {{- include "parca.labels.agent" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "parca.selectorLabels.agent" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        parca: {{ include "parca.fullname" . }}-agent
        {{- include "parca.selectorLabels.agent" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "parca.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-agent
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          args:
            - /bin/parca-agent
            - --log-level={{ .Values.agent.logLevel }}
            - --node=$(NODE_NAME)
            - --kubernetes
            - --store-address={{ include "parca.fullname" . }}-server.{{ .Release.Namespace }}.svc.cluster.local:7070
            - --insecure
            - --insecure-skip-verify
            - --temp-dir=/tmp
            - --socket-path={{ .Values.agent.socketPath }}
            {{- if .Values.agent.podLabelSelector }}
            - --pod-label-selector={{ .Values.agent.podLabelSelector }}
            {{- end }}
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          ports:
          - containerPort: 7071
            hostPort: 7071
            name: http
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /run
            name: run
          - mountPath: /lib/modules
            name: modules
          - mountPath: /sys/kernel/debug
            name: debugfs
          - mountPath: /sys/fs/cgroup
            name: cgroup
          - mountPath: /sys/fs/bpf
            name: bpffs
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      hostPID: true
      volumes:
      - emptyDir: {}
        name: tmp
      - hostPath:
          path: /run
        name: run
      - hostPath:
          path: /sys/fs/cgroup
        name: cgroup
      - hostPath:
          path: /lib/modules
        name: modules
      - hostPath:
          path: /sys/fs/bpf
        name: bpffs
      - hostPath:
          path: /sys/kernel/debug
        name: debugfs
      serviceAccountName: {{ include "parca.serviceAccountName" . }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}